version: "3"
services:
  app:
    container_name: app_container
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    volumes:
      - ./app
      - /node_modules
  db:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: battleship-db
    ports:
      - '5432:5432'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    networks:
      - battleshipNetwork
    restart: always
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - battleshipNetwork
    restart: always
volumes:
  pgadmin-data:
networks:
  battleshipNetwork:
    driver: bridge

